on: [ pull_request, push ]
name: ci
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin main
    - uses: flux-framework/pr-validator@master

  ci-checks:
    runs-on: ubuntu-latest
    env:
      TAP_DRIVER_QUIET: 1
      FLUX_TEST_TIMEOUT: 300
    timeout-minutes: 20
    strategy:
      matrix:
        include:
        - name: "focal"
          image: "focal"
          create_release: true
          env:
            DISTCHECK: t
        - name: "el8"
          image: "el8"
          env:
            chain_lint: t
        - name: "fedora35"
          image: "fedora35"
          env: {}
      fail-fast: false
    name: ${{ matrix.name }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}
       fetch-depth: 0

    - name: get tag name
      id: tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

    - name: docker-run-checks
      env: ${{ matrix.env }}
      run: >
        ./src/test/docker/docker-run-checks.sh
        -j $(nproc)
        -i ${{ matrix.image }}
        --

    - name: annotate errors
      if: failure() || cancelled()
      run: src/test/checks-annotate.sh

    - name: create release
      id: create_release
      if: success() && matrix.create_release && startswith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.output.name }}
        release_name: flux-pam ${{ steps.tag.output.name }}
        prerelease: true
        body: |
          View [Release Notes](https://github.com/${{ github.repository }}/blob/${{ matrix.tag }}/NEWS.md) for flux-accounting ${{ matrix.tag }}
        files: flux-pam*.tar.gz
